export type IKmEvent =
  | 'CONNECTED'
  | 'DISCONNECTED'
  | 'NOTIFICATIONS'
  | 'UPDATE_READ_NOTIFICATIONS'
  | 'UPDATE_READ_NOTIFICATIONS_RESULT'


export interface IKmEventConstant {
  CONNECTED: IKmEvent;
  DISCONNECTED: IKmEvent;
  NOTIFICATIONS: IKmEvent;
  UPDATE_READ_NOTIFICATIONS: IKmEvent;
  UPDATE_READ_NOTIFICATIONS_RESULT: IKmEvent;
}
export const KmEvent: IKmEventConstant = {
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  NOTIFICATIONS: 'NOTIFICATIONS',
  UPDATE_READ_NOTIFICATIONS: 'UPDATE_READ_NOTIFICATIONS',
  UPDATE_READ_NOTIFICATIONS_RESULT: 'UPDATE_READ_NOTIFICATIONS_RESULT',
};

